name: CI
on:
  push:
    branches:
      - main
    tags:
      - "web-[0-9]+.[0-9]+.[0-9]+"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version-file: ./.node-version
          cache: npm
      - run: |
          npm install
          make web
          npm run test
  deploy:
    needs: test
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/web-')
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: get-version
        run: |
          version=$(echo ${{ github.ref }} | cut -d- -f2)
          echo "version=$version" >> $GITHUB_OUTPUT
      - run: echo "version=${{ steps.get-version.outputs.version }}"
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/configure-pages@v5
      - name: Build
        env:
          KSESH_VERSION: ${{ steps.get-version.outputs.version }}
        run: |
          npm install
          make
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './public'
      - uses: actions/deploy-pages@v4
